### ISSUE TITLE
How do I enable Use relative paths?

### ISSUE THREAD

**Issue by tacroya** [riccardobl/blender_effekseer_addon#8]
Unable to enable Use relative paths.
I don't know if it has anything to do with that, but the effect is also a black plane.
<img width="138" alt="スクリーンショット 2023-12-26 135431" src="https://github.com/riccardobl/blender_effekseer_addon/assets/118147967/3b74506f-6848-4dfb-bf67-8bbd8ca594d6">

<img width="931" alt="スクリーンショット 2023-12-26 135529" src="https://github.com/riccardobl/blender_effekseer_addon/assets/118147967/0f568097-ab36-4ce3-a0b9-0ffeb7ae1fb0">

**Comment by riccardobl** [comment]
Do you see any error in the console?
This addon uses an hack to hijack the rendering thread of blender, so it is breaks easily with updates, if i recall correctly, it was developed for blender 2.8

**Comment by tacroya** [comment]
Thank you for your reply.
The cause was that I had never saved the project.

However, I ended up not knowing how to use the add-on itself, so I stopped using it.
